source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'MeFocus' do

  # Pods for MeFocus
  pod 'HGCircularSlider'
  pod 'Lock', '~> 1.27'
  pod 'SimpleKeychain', '~> 0.7'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'AutoCompleteTextField'
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
end
